import "@fontsource-variable/inter";
import "./globals.css";

export const metadata = {
  title: "Office of Suspicion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen app-gradient">
        <main className="mx-auto max-w-6xl px-4 py-10 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
